language: node_js
node_js:
  - "9"
sudo: required
dist: trusty
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  directories:
  - $HOME/.npm
install:
  - npm i -g npm@6.0.1
  - npm ci
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng test
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN
